services:
  postgres:
    container_name: postgres_prod_def
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: