spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: payment
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    drop-first: false
