spring:
  datasource:
    url: jdbc:postgresql://dpg-d3fpekvfte5s73dd4gi0-a:5432/postgres_m5zf
    username: postgres_m5zf_user
    password: ZVRUxHBbZ3SHWyAQYlHUev3DyOFXxA2h
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    drop-first: false